Proyecto/iteracion1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sistema.urls')),
]

Proyecto/sistema/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'sistema'

urlpatterns = [
	# LANDING
	path('landingpage/', views.index_landing_admin, name='index_landing_admin'),

    # LOGIN
    path('login/', views.index_login, name = 'index_login'),
    path('login/val', views.login_validate, name = 'login_val'),
    path('logout/', views.log_out, name = 'logout'),
	
    # INDICES
    path('cursos/', views.index_cursos, name = 'index_cursos'),
    path('evaluaciones/', views.index_evaluaciones, name = 'index_evaluaciones'),
    path('evaluadores/', views.index_evaluadores, name = 'index_evaluadores'),
    path('rubricas/', views.index_rubricas, name = 'index_rubricas'),
	
	# EVALUACION
    path('evaluaciones/<int:eval_id>/', views.evaluacion, name = 'evaluacion'),
    path('evaluaciones/<int:eval_id>/agregar', views.evaluacion_agr_evaluador, name='evaluacion_agr_evaluador'),
    path('evaluaciones/<int:eval_id>/eliminar', views.evaluacion_eliminar_evaluador, name='evaluacion_eliminar_evaluador'),
    path('evaluaciones/<int:eval_id>/grupo/<int:grupo_id>/<int:rubrica_id>', views.evaluacion_grupo, name='evaluacion_grupo'),
    path('evaluaciones/<int:eval_id>/grupo/<int:grupo_id>/post/<int:rubrica_id>', views.postevaluacion , name='postevaluacion'),
	
	# RUBRICA
    path('rubricas/<int:rubrica_id>/', views.rubrica, name = 'rubrica'),
    path('rubricas/<int:rubrica_id>/editar', views.rubrica_editar, name = 'rubrica_editar'),
	
	# GESTIONAR EVALUADORES
    path('evaluadores/agregar/', views.agregar_evaluador, name = 'evaluador_agr'),
    path('evaluadores/modificar/', views.modificar_evaluador, name = 'evaluador_mod'),
    path('evaluadores/eliminar/', views.eliminar_evaluador, name = 'evaluador_eli'),
	
	# GESTIONAR RUBRICAS
    path('rubricas/agregar/', views.agregar_rubrica, name = 'rubrica_agr'),
    path('rubricas/<int:rubrica_id>/guardar', views.modificar_rubrica, name = 'rubrica_mod'),
    path('rubricas/eliminar/', views.eliminar_rubrica, name = 'rubrica_eli'),
	
	# GESTIONAR EVALUACIONES
    path('evaluaciones/agregar/', views.agregar_evaluacion, name = 'evaluacion_agr'),
    path('evaluaciones/modificar/', views.modificar_evaluacion, name = 'evaluacion_mod'),
    path('evaluaciones/eliminar/', views.eliminar_evaluacion, name = 'evaluacion_eli'),

    # REDIRECT
    path('', views.home)
]

Proyecto/sistema/models.py
from django.db import models
from django.db import models
from django.utils import timezone

import os

# Create your models here.
from django.utils.datetime_safe import datetime


class Grupo(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre

class Alumno(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField(max_length=90)
    rut = models.CharField(max_length=10)
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class HistorialGrupos(models.Model):
    alumno= models.ForeignKey(Alumno,on_delete=models.CASCADE)
    grupo = models.ForeignKey(Grupo,on_delete=models.CASCADE)
    fecha = models.DateField()

    def __str__(self):
        return self.grupo + ", " + self.fecha

class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre + " " + self.codigo

class Instancia(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    ano=models.IntegerField()
    semestre= models.CharField(max_length=100)
    seccion=models.IntegerField()

    def __str__(self):
        return " ".join([self.curso.nombre, self.semestre, str(self.ano), "Sección", str(self.seccion)])

class InstanciaGrupo(models.Model):
    instancia = models.ForeignKey(Instancia, on_delete=models.CASCADE)#sin on delete tira error
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)#sin on delete tira error

    def __str__(self):
        return str(self.instancia) +" "+ str(self.grupo)

class Evaluacion(models.Model):
    instancia = models.ForeignKey(Instancia, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, default="Evaluacion")
    fecha_inicio=models.DateField()
    fecha_fin=models.DateField()

    def __str__(self):
        return str(self.fecha_inicio)

    # True si fecha_inicio es posterio a fecha actual (al agregar)
    # y fecha_fin es posterior a fecha_inicio
    def validar_fechas(self, agregar=False):
        if agregar and not (self.fecha_inicio >= timezone.now().date()):
            return False
        return self.fecha_inicio <= self.fecha_fin

    # True si fecha actual esta entre fecha_inicio y fecha_fin
    def abierta(self):
        return self.fecha_inicio <= timezone.now().date() <= self.fecha_fin

    # True si la evaluacion ya se realizo
    def realizada(self):
        return self.fecha_fin < timezone.now().date()

class Evaluador(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField(max_length=90)
    password=models.CharField(max_length=100)
    es_admin=models.BooleanField()

    def __str__(self):
        return self.nombre

class Rubrica(models.Model):
    nombre=models.CharField(max_length=100)
    archivo=models.FileField(upload_to=None, max_length=100)
    tiempo_min=models.TimeField(default='00:00:00')
    tiempo_max=models.TimeField(default='00:00:00')
    t = None # tabla donde se guarda la info de archivo

    def __str__(self):
        return self.nombre

    # Crea el archivo y devuelve su ruta
    def crear(self):
        fn = "rubricas/rubrica_{}.csv".format(self.id)
        f = open(fn, "w")
        f.writelines(["$0.0\n","Aspecto1$Descripcion1\n"])
        f.close()
        return fn

    # Carga y devuelve los datos de la rubrica
    def tabla(self):
        if self.t == None:
            f = open(str(self.archivo), "r")
            self.t = [line.rstrip('\n').split('$') for line in f]
            f.close()
        return self.t

    # Devuelvelos niveles de cumplimiento
    def niveles(self):
        if self.t == None:
            self.tabla()
        return self.t[0][1:]

    # Devuelve los aspectos a evaluar
    def aspectos(self):
        if self.t == None:
            self.tabla()
        return [self.t[i][0] for i in range(1, len(self.t))]

    # Borra el archivo asociado
    def borrar(self):
        os.remove(str(self.archivo))

    # Modifica el archivo de acuerdo a la tabla entregada
    def modificar(self, tabla):
        tabla = self.reordenar(tabla)
        f = open(str(self.archivo), "w")
        for linea in tabla:
            f.write("$".join(linea) + "\n")
        self.t = None

    # Reordena las celdas en puntaje de menor a mayor
    def reordenar(self, tabla):
        nt = [[tabla[i].pop(0)] for i in range(len(tabla))]
        while len(tabla[0]) > 0:
            i = tabla[0].index(min(tabla[0]))
            for j in range(len(tabla)):
                nt[j].append(tabla[j].pop(i))
        return nt

    # True si el puntaje maximo es 6.0
    def validar(self):
        t = self.tabla()
        pmax = float(t[0][-1])
        return int(10 * pmax * (len(t) - 1)) == 60

class EvaluacionRubrica(models.Model):
    evaluacion = models.ForeignKey(Evaluacion,on_delete=models.CASCADE)
    rubrica = models.ForeignKey(Rubrica,on_delete=models.CASCADE)

class Presentacion(models.Model):
    presentador=models.CharField(max_length=100)
    evaluador=models.CharField(max_length=100)
    puntajes=models.CharField(max_length=100)
    evaluacion = models.ForeignKey(Evaluacion,on_delete=models.CASCADE)
    tiempo=models.TimeField(default='00:00:00')
    descuento=models.IntegerField(default=0)
    grupo = models.ForeignKey(Grupo,on_delete=models.CASCADE)

class Evalua(models.Model):
    evaluacion = models.ForeignKey(Evaluacion,on_delete=models.CASCADE)
    evaluador = models.ForeignKey(Evaluador,on_delete=models.SET_DEFAULT, default=1)
    puso_nota=models.BooleanField(default=False)


Proyecto/sistema/forms.py
from django import forms

class EvaluadorForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    correo = forms.EmailField(max_length=90)

class EvaluacionForm(forms.Form):
    inicio = forms.DateField()
    fin = forms.DateField()

Proyecto/sistema/templates/sistema/Landing_page_admin.html
<!DOCTYPE html>
<html lang="es">
<title>Plataforma de evaluación</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
    <!--Profile image -->
  <div class="w3-container">
      <p class="w3-center"><img src="https://www.w3schools.com/w3images/avatar3.png" class="w3-circle" style="height:200px;width:200px" alt="Avatar"></p>
    <h3 class="w3-padding-64"><center><b>Usuario</b></center></h3>
  </div>
  <div class="w3-bar-block">
    <a href="#" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
    <a href="#cursos" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Cursos</a>
    <a href="#evaluadores" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluadores</a>
      <a href="#rubricas" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Rúbricas</a>
    <a href="#evaluaciones" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluaciones</a>
    <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact</a>
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>Usuario</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px"

  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:300px; margin-bottom:300px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Bienvenido al sistema de evaluación</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <p><h3>Seleccione alguna sección para comenzar</p></h2>
     <i class="far fa-arrow-alt-circle-left" style="font-size:300%"></i>
  </div>

<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-16" style="margin-top:50px;padding-right:58px">
  <div class="bottom" id="contact" style="margin-top:50px>
    <h1 class="w3-xxlarge w3-text-red"><b>Contacto.</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
    <p>¿Dudas? ¿Sugerencias? ¿Reclamos?</p>
      <p>No dude en contactarnos</p>
    <form action="/action_page.php" target="_blank">
      <div class="w3-section">
        <label>Nombre</label>
        <input class="w3-input w3-border" type="text" name="Name" required>
      </div>
      <div class="w3-section">
        <label>Email</label>
        <input class="w3-input w3-border" type="text" name="Email" required>
      </div>
      <div class="w3-section">
        <label>Mensaje</label>
        <input class="w3-input w3-border" type="text" name="Message" required>
      </div>
      <button type="submit" class="w3-button w3-red w3-margin-bottom">Enviar</button>
    </form>
  </div>
</div>
    <p class="w3-right">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">w3.css</a></p>
</div>
<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

</body>
</html>

Proyecto/sistema/templates/sistema/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
<title>Plataforma de evaluación - {% block subtitle %}{% endblock %}</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="{% static 'Script/w3.css' %}">
<link rel="stylesheet" href="{% static 'Script/all.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">


  <style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
.opcion.w3-padding-16:hover{
  opacity:0.5;
  color: rgb(0, 110, 255);
  cursor: pointer;
}
.selected{
  background-color:#A2A2A2;
}

</style>
</head>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-blue w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:200px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:18px">Cerrar </a>
    <!--Profile image -->
  <div class="w3-container">
    <h3 class="w3-padding-32"><center><b>{% block user %}{% endblock %}</b></center></h3>
  </div>
  <div class="w3-bar-block">
    <a href="{% url 'sistema:index_landing_admin' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
    {% if request.session.es_admin %}<a href="{% url 'sistema:index_cursos' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Cursos</a>
    <a href="{% url 'sistema:index_evaluadores' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluadores</a>
    <a href="{% url 'sistema:index_rubricas' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Rúbricas</a> {% endif %}
    <a href="{% url 'sistema:index_evaluaciones' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Evaluaciones</a>
   <!-- <a href="#contact" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact</a> -->
  </div>

  <a href="{% url 'sistema:logout' %}" onclick="w3_close()" class="w3-button w3-display-bottomright" style="width:100%;font-size:17px">Salir </a>
 </nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-blue w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-blue w3-margin-right" onclick="w3_open()">☰</a>
  <span >{% block name %}{% endblock %}</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:240px;margin-right:40px">

  {% block content %}{% endblock %}

</div>
<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

</body>
</html>

Proyecto/sistema/templates/sistema/landing.html
{% extends "sistema/base.html" %}
{% block subtitle %}Landing{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}
{% block name %} {{request.session.nombre}}{% endblock %}
{% block content %}

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-right:40px">
  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:30px">
    <h1  class="w3-xxxlarge w3-text-black"><b>Bienvenido al sistema de evaluación</b></h1>
    <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
    <p><h3>Seleccione alguna sección para comenzar</h3></p>
     <i class="fas fa-arrow-left" style="font-size:300%"></i>
  </div>
</div>
<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>
{% endblock %}

Proyecto/sistema/templates/sistema/landingevaluador.html
{% extends "sistema/base.html" %}

{% load i18n %}
{% block subtitle %}Landing{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}
{% block content %}
<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-right:40px">
  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:30px">
    <h1 class="w3-xxxlarge w3-text-black"><b>Bienvenido al sistema de evaluación</b></h1>

  </div>
<div class="w3-row-padding w3-center w3-margin-top" style="margin-bottom: 64px">
{% for evaluacion in lista_evaluaciones %}
<div class="w3-col m6 l4 w3-margin-top">
 <div class="w3-card-4">

<header class="w3-container w3-light-grey">
  <h3>{{evaluacion.nombre}}</h3>
</header>

<div class="w3-container">
  <p>{{evaluacion.instancia}}</p>
  <!--<p id="status"> PENDIENTE</p>
  {{evaluacion.presentacion_set.all }}-->
  <hr>
  <p>
      {% language 'es' %}
    <li>Fecha inicio: {{ evaluacion.fecha_inicio }}</li>
    <li>Fecha término: {{ evaluacion.fecha_fin }}</li>
    {% endlanguage %}
  </p>
</div>

<button onclick="location.href='{% url 'sistema:evaluacion' eval_id=evaluacion.id %}'" class="w3-button w3-block w3-blue">Ver</button>

</div>
</div>
{% endfor %}
</div>

</div>
<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>
{% endblock %}

Proyecto/sistema/templates/sistema/login.html
{% block content %}
<html lang="es">
<title>Plataforma de evaluación</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
<body>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-large w3-blue w3-xlarge w3-padding"></header>
<br>
       <!--Profile image -->
  <div class="w3-container" style="margin">
      <p class="w3-center"><img src="https://www.w3schools.com/w3images/avatar3.png" class="w3-circle" style="height:200px;width:200px" alt="Avatar"></p>
      <h1 class=" w3-text-black w3-center" style="font-size:3vw;"><b>Bienvenido al sistema de evaluación</b></h1>

     
      <form action="{% url 'sistema:login_val' %} " method="post">
          {% csrf_token %}
    <div class="w3-center" style="">
        Correo electronico:
        <br>
  <input type="text" name="correo" placeholder="Ejemplo@gmail.com" required>
        <br>
  Contraseña:
        <br>
  <input type="password" name="password" placeholder="*****" required>
         {% if error %}
            <p class="w3-text-red">{{error}}</p>
        {% endif %}
         {% if not error %}<br>  <br>{% endif %}

  <input type="submit" value="Ingresar">
          </div>
</form> 

    </div>
<footer class="w3-container w3-bottom w3-large w3-blue w3-xlarge w3-padding"></footer>

</body>

{% endblock %}