Proyecto/iteracion1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sistema.urls')),
]

Proyecto/sistema/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'sistema'

urlpatterns = [
	# LANDING
	path('landingpage/', views.index_landing_admin, name='index_landing_admin'),

    # LOGIN
    path('login/', views.index_login, name = 'index_login'),
    path('login/val', views.login_validate, name = 'login_val'),
    path('logout/', views.log_out, name = 'logout'),
	
    # INDICES
    path('cursos/', views.index_cursos, name = 'index_cursos'),
    path('evaluaciones/', views.index_evaluaciones, name = 'index_evaluaciones'),
    path('evaluadores/', views.index_evaluadores, name = 'index_evaluadores'),
    path('rubricas/', views.index_rubricas, name = 'index_rubricas'),
	
	# EVALUACION
    path('evaluaciones/<int:eval_id>/', views.evaluacion, name = 'evaluacion'),
    path('evaluaciones/<int:eval_id>/agregar', views.evaluacion_agr_evaluador, name='evaluacion_agr_evaluador'),
    path('evaluaciones/<int:eval_id>/eliminar', views.evaluacion_eliminar_evaluador, name='evaluacion_eliminar_evaluador'),
    path('evaluaciones/<int:eval_id>/grupo/<int:grupo_id>/<int:rubrica_id>', views.evaluacion_grupo, name='evaluacion_grupo'),
    path('evaluaciones/<int:eval_id>/grupo/<int:grupo_id>/post/<int:rubrica_id>', views.postevaluacion , name='postevaluacion'),
	
	# RUBRICA
    path('rubricas/<int:rubrica_id>/', views.rubrica, name = 'rubrica'),
    path('rubricas/<int:rubrica_id>/editar', views.rubrica_editar, name = 'rubrica_editar'),
	
	# GESTIONAR EVALUADORES
    path('evaluadores/agregar/', views.agregar_evaluador, name = 'evaluador_agr'),
    path('evaluadores/modificar/', views.modificar_evaluador, name = 'evaluador_mod'),
    path('evaluadores/eliminar/', views.eliminar_evaluador, name = 'evaluador_eli'),
	
	# GESTIONAR RUBRICAS
    path('rubricas/agregar/', views.agregar_rubrica, name = 'rubrica_agr'),
    path('rubricas/<int:rubrica_id>/guardar', views.modificar_rubrica, name = 'rubrica_mod'),
    path('rubricas/eliminar/', views.eliminar_rubrica, name = 'rubrica_eli'),
	
	# GESTIONAR EVALUACIONES
    path('evaluaciones/agregar/', views.agregar_evaluacion, name = 'evaluacion_agr'),
    path('evaluaciones/modificar/', views.modificar_evaluacion, name = 'evaluacion_mod'),
    path('evaluaciones/eliminar/', views.eliminar_evaluacion, name = 'evaluacion_eli'),

    # REDIRECT
    path('', views.home)
]

Proyecto/sistema/forms.py
from django import forms

class EvaluadorForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    correo = forms.EmailField(max_length=90)

class EvaluacionForm(forms.Form):
    inicio = forms.DateField()
    fin = forms.DateField()

Proyecto/sistema/views.py
from django.shortcuts import render, redirect, reverse
from django.utils.crypto import random
from django.contrib.auth.decorators import login_required

from .models import Instancia, Evaluador, Evaluacion, Rubrica, Grupo, EvaluacionRubrica, Evalua, InstanciaGrupo, \
    Presentacion
from .forms import EvaluadorForm, EvaluacionForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Contraseña
abc = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
def nueva_pass():
    #Genera pass aleatoria
	p = ""
	for _ in range(16):
		p += abc[random.randint(0, len(abc)-1)]
	return p

# Rubrica tiene notas
def rubrica_sin_uso(rubrica):
    # Obtengo evaluaciones que usan esta rubrica
    evaluaciones_con_rubrica = rubrica.evaluacionrubrica_set.all()
    evaluaciones=[]
    for eval in evaluaciones_con_rubrica:
        evaluaciones.append(eval.evaluacion)

    puede_editar = True

    for evaluacion in evaluaciones:
        numero_notas_puestas_de_evaluacion=Presentacion.objects.filter(evaluacion=evaluacion).count()
        if(numero_notas_puestas_de_evaluacion>0):
            puede_editar=False
            break
        
    return puede_editar


#   LOGIN
def login_validate(request):
    #Si se ha ingresado mediante login
    if request.method == "POST":
        #Verifica si el correo y la contraseña ingresada es valida
        mail=request.POST['correo']
        passw=request.POST['password']
        user = authenticate(username= mail, password=passw)
        #
        if (user) is not None:
            login(request, user)
            eval = Evaluador.objects.get(correo=mail)
            #Creo variables de sessiones para tener informacionn de la persona
            #que entro por login
            request.session['correo'] = mail
            request.session['es_admin'] = eval.es_admin
            request.session['nombre']=eval.nombre
            return redirect(reverse("sistema:index_landing_admin"))
        else:
            user_exist = User.objects.filter(username=mail).count() > 0
            if user_exist:
                mensaje = "La contraseña ingresada no es válida"
            else:
                mensaje = "El correo ingresado no existe"
            context = {
                'error': mensaje
            }
            return render(request, 'sistema/login.html', context)
    return redirect(reverse("sistema:index_login"))

def log_out(request):
    #Setea las variables de session para reconocer el usuario en None
    logout(request)
    request.session['correo'] = None
    request.session['es_admin'] = None
    request.session['nombre'] = None
    return redirect(reverse("sistema:index_login"))

#   INDICES
@login_required
def index_landing_admin(request):
    #Si es admin, muestra el landing page de admin
    if request.session.get('es_admin'):
        return render(request, 'sistema/landing.html')
    else:
        #Obtiene evaluador a traves de variables de session correo
        eval = Evaluador.objects.get(correo=request.session.get('correo'))
        #Saca todas las evaluaciones que le corresponden al evaluador
        evaluas = eval.evalua_set.all()
        Evaluaciones = []
        for evalua in evaluas:
            Evaluaciones.append(evalua.evaluacion)
        # Luego ordeno las evaluaciones por la fecha de inicio
        evaluaciones_order = sorted(Evaluaciones, key=lambda x: x.fecha_inicio,reverse=True)
        context = {
            'lista_rubricas': Rubrica.objects.all(),
            'lista_evaluaciones': evaluaciones_order[:10],
            'lista_cursos': Instancia.objects.all()
        }
        return render(request, 'sistema/landingevaluador.html', context)

def index_login(request):
    #Dirige al login
    return render(request,'sistema/login.html')

@login_required
def index_cursos(request):
    #Muestra todos los cursos
    context = {
        'lista_cursos': Instancia.objects.all()
    }
    return render(request, 'sistema/admin/pag_cursos.html', context)

# error = True  fechas incorrectas (ver Evaluacion.validar_fechas)
@login_required
def index_evaluaciones(request, error = False):
    #Si es admin
    if request.session.get('es_admin'):
        #Muestra todas las evaluaciones
        context = {
            'lista_rubricas': Rubrica.objects.all(),
            'lista_evaluaciones': Evaluacion.objects.all(),
            'lista_cursos': Instancia.objects.all()
        }
    else:
        #Rescata las evaluaciones asociadas al evaluador
        eval=Evaluador.objects.get(correo=request.session.get('correo'))
        evaluas=eval.evalua_set.all()
        Evaluaciones=[]
        for evalua in evaluas:
            Evaluaciones.append(evalua.evaluacion)

        context = {
            'lista_rubricas': Rubrica.objects.all(),
            'lista_evaluaciones': Evaluaciones,
            'lista_cursos': Instancia.objects.all()
        }

    if error:
        context['mensaje'] = "Las fechas ingresadas son incorrectas"
    return render(request, 'sistema/admin/pag_evaluaciones.html', context)

# error = 1     email repetido
# error = 2     email incorrecto
@login_required
def index_evaluadores(request, error = 0, nombre = None):
    if error == 1:
        mensaje = "El correo ya se encuentra registrado"
    elif error == 2:
        mensaje = "El correo ingresado no es válido"
    context = {
        #id 1 es evaluadores eliminados
        #id 2 es el admin
        #Filtra los valores mayores a gt
            'lista_evaluadores': Evaluador.objects.filter(id__gt=2)
    }
    if error:
        context['mensaje'] = mensaje
        context['nombre'] = nombre
    return render(request, 'sistema/admin/pag_evaluadores.html', context)

@login_required
def index_rubricas(request):
    #Entrega todas las rubricas
    context = {
        'lista_rubricas': Rubrica.objects.all()
    }
    return render(request, 'sistema/admin/pag_rubricas.html', context)


#   EVALUACION
@login_required
def evaluacion(request, eval_id):
    #Evaluacion
    ev = Evaluacion.objects.get(pk=eval_id)
    #Evaluadores que no son admin
    evaluadores = Evaluador.objects.filter(es_admin=0)
    # Evaluadores que son admin
    evaluadores_admin = Evaluador.objects.filter(es_admin=1)
    id_eval_admin=[]
    for eval in evaluadores_admin:
        id_eval_admin.append(eval.id)
    # Evaluadores de la evaluacion que no son admin
    evaluadores_eval = ev.evalua_set.all().exclude(evaluador_id__in=id_eval_admin)
    for eval in evaluadores_eval:
        id_eval_admin.append(eval.evaluador_id)
    #Evaluadores que se pueden agregar
    evaluadores_para_agregar=evaluadores.exclude(id__in=id_eval_admin)

    # grupos del curso de la evaluacion
    grupos = InstanciaGrupo.objects.filter(instancia=ev.instancia)
    context = {
		'evaluacion': ev,
        'lista_grupos': grupos,
        'lista_evaluadores':  evaluadores_para_agregar,
        'lista_evalua':evaluadores_eval
    }

    return render(request, 'sistema/evaluacion/gruposevaluacion.html',context)

@login_required
def evaluacion_grupo(request,eval_id=0,grupo_id=0,rubrica_id=0):
    #Entrega evaluacion grupo y rubrica que estan relacionadas
    ev = Evaluacion.objects.get(pk=eval_id)
    gr = Grupo.objects.get(pk=grupo_id)
    rub = Rubrica.objects.get(pk=rubrica_id)
    context = {
        'evaluacion': ev,
        'grupo' : gr,
        'rubrica':rub,
        'puntajes': rub.niveles
    }
    #Si esta en curso la evaluación
    if ev.abierta():
        #Si es admin
        if request.session.get('es_admin'):
            return render(request,'sistema/evaluacion/evaluacionadmin.html',context)
        else:
            return render(request, 'sistema/evaluacion/evaluacion.html', context)
    #Si ya termino
    return render(request, 'sistema/evaluacion/posteval.html',context)

@login_required
def postevaluacion(request, eval_id=0,grupo_id=0,rubrica_id=0):
    if request.method == "POST":
        #Rescata evaluacion, grupo, rubrica, puntajes y puntajes base de la evaluacion
        ev = Evaluacion.objects.get(pk=eval_id)
        gr = Grupo.objects.get(pk=grupo_id)
        rub = Rubrica.objects.get(pk=rubrica_id)
        puntaje=request.POST['lista-puntajes'].split(',')
        puntaje_base=(request.POST['lista-pj-base'])
        # Crear evaluacion de grupo si aun no esta en el sistema
        pre = Presentacion.objects.filter(evaluacion=ev,
                                          grupo=gr,evaluador=request.session.get('nombre')).exists()
        # Si no existe la presentacion se crea
        if not (pre):
            if(request.session.get('es_admin')):
                #Saca los presentadores que fueron agregados
                presentadores = (request.POST['presentadores_grupo']).split(',')
                pre = Presentacion.objects.create(evaluacion=ev,
                                              grupo=gr,
                                              puntajes=puntaje,
                                              evaluador=request.session.get('nombre'),
                                              presentador=presentadores,
                                              tiempo=request.POST['tiempo_presentacion'],
                                              descuento=int(request.POST['descuento_tiempo']))
                descuento = request.POST['descuento_tiempo']
            else:
                #Crea nueva presentacion en donde se registra el puntaje
                pre = Presentacion.objects.create(evaluacion=ev,
                                                  grupo=gr,
                                                  puntajes=puntaje,
                                                  evaluador=request.session.get('nombre'))

Proyecto/sistema/templates/sistema/rubricas/rubrica.html
{% extends "sistema/base.html" %}

{% block subtitle %}Rúbricas{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}
{% block content %}

<!-- Portada -->
<div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
  <h1 class="w3-xxxlarge w3-text-black"><b>Ficha de rúbrica</b></h1>
  <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
  <p><h3>{{ rubrica.nombre }}</h3></p>
  {% if not editable %}<p style="color: goldenrod">No se puede editar la rúbrica porque tiene notas asociadas</p>{% endif %}
</div>

<div>
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
      margin: 20px 0.5% 0.5%;
      font-size: 15px;
    }

    td {
      border: 1px solid #665f5f;
      text-align: left;
      width: 12%;
      padding: 1%;
    }

    th {
      border: 1px solid #665f5f;
      text-align: right;
      width: 12%;
      padding: 1%;
    }

    tr:nth-child(even) {
      background-color: #9CA5AB;
    }

  </style>
    <div class="w3-section">
        <div class="w3-half">
          <label><b>Tiempo mínimo </b></label>
          {{rubrica.tiempo_min|time:'H:i'}}
        </div>
        <div class="w3-half">
            <label><b>Tiempo máximo</b></label>
                    {{rubrica.tiempo_max|time:'H:i'}}
        </div>
    </div>
  <br>
  <table>
    <tr>
      {% for celda in rubrica.tabla.0 %}
        <th>{{ celda }}</th>
      {% endfor %}
    </tr>
    {% for fila in rubrica.tabla %}
    {% if not forloop.first %}
    <tr>
      {% for celda in fila %}
      <td>{% if forloop.first %}<b>{% endif %}{{ celda }}{% if forloop.first %}</b>{% endif %}</td>
      {% endfor %}
    </tr>
    {% endif %}
    {% endfor %}
  </table>
</div>

<div>
  {% if not rubrica.validar %}<p>La rúbrica no tiene el puntaje máximo adecuado (6 puntos).</p>{% endif %}
  {% if request.session.es_admin and editable %}
  <a href="{% url 'sistema:rubrica_editar' rubrica_id=rubrica.id %}">
    <button class="w3-btn w3-blue w3-large w3-margin-top" style="margin-bottom: 64px">Editar <i class="fas fa-edit"></i></button>
  </a>
  {% endif %}
  <a href="{% url 'sistema:index_rubricas' %}">
    <button class="w3-btn w3-right w3-blue w3-large w3-margin-top" style="margin-bottom: 64px">Volver <i class="fas fa-arrow-left"></i></button>
  </a>

</div>

{% endblock %}

Proyecto/sistema/templates/sistema/rubricas/rubrica_admin.html
{% extends "sistema/base.html" %}

{% block subtitle %}Rúbricas{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}
{% block content %}

<!-- Portada -->
<div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
  <h1 class="w3-xxxlarge w3-text-black"><b>Editar rúbrica</b></h1>
  <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
  <h3 id="nombreTitulo">{{ rubrica.nombre }} 
    <button onclick="document.getElementById('cambiar_nombre').style.display='block'" class="w3-button w3-medium w3-transparent w3-display"><i class="fas fa-edit"></i></button></h3><br>
</div>

<div>
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: fit-content;
      margin: 10px 0.5% 0.5%;
    }

    td, th {
      border: 1px solid #665f5f;
      text-align: left;
      width: 12%;
      padding: 5px;
    }

    tr:nth-child(even) {
      background-color: #9CA5AB;
    }
  </style>
  <form action="{% url 'sistema:rubrica_mod' rubrica_id=rubrica.id %}" method="POST">
    {% csrf_token %}
    <input id="nombre" type=hidden name="nombre" value="{{ rubrica.nombre }}">
    <div class="w3-section">
        <div class="w3-half">
          <label><b>Tiempo mínimo </b></label>
          <input class="w3-input w3-border w3-margin-bottom w3-center" type="time" value="{{rubrica.tiempo_min|time:'H:i'}}" required name="minimo">
        </div>
        <div class="w3-half">
            <label><b>Tiempo máximo</b></label>
            <input class="w3-input w3-border w3-margin-bottom w3-center" type="time" value="{{rubrica.tiempo_max|time:'H:i'}}" required name="maximo">
        </div>
    </div>
    <table id="tabla">
      <tr>
        {% for celda in rubrica.tabla.0 %}
          <th>
            {% if forloop.first %}
            <input type="hidden" name="celda:0,0" value:{{ celda }}>
            {% else %}
            <span onclick="eliminar_nivel({{ forloop.counter0 }})" class="w3-button w3-right w3-medium w3-transparent w3-col" style="width:40px"><i class="fas fa-times"></i></span>
            <input class="w3-input w3-border w3-col" style="width:60px" type="number" name="celda:0,{{ forloop.counter0 }}" min="0" max="6" step="0.1" value="{{ celda }}">
            {% endif %}
          </th>
        {% endfor %}
      </tr>
      {% for fila in rubrica.tabla %}
      {% with forloop.counter0 as row %}
      {% if not forloop.first %}
      <tr>
        {% for celda in fila %}
        <td>
          {% if forloop.first %}<span onclick="eliminar_criterio({{ row }})" class="w3-button w3-right w3-medium w3-transparent w3-col" style="width:40px"><i class="fas fa-times"></i></span>{% endif %}
          <textarea class="w3-input w3-border" style="resize:none" name="celda:{{ row }},{{ forloop.counter0 }}" maxlength="200" rows="{% if forloop.first %}2{% else %}3{% endif %}" wrap="soft">{{ celda }}</textarea>
        </td>
        {% endfor %}
      </tr>
      {% endif %}
      {% endwith %}
      {% endfor %}
    </table>
    <div class="w3-twothird">
      <button type="button" onclick="agregar_criterio()" class="w3-btn w3-blue w3-large w3-margin-top">Agregar criterio <i class="fas fa-plus"></i></button>
      <button type="button" onclick="agregar_nivel()" class="w3-btn w3-blue w3-large w3-margin-top">Agregar nivel <i class="fas fa-plus"></i></button>
    </div>
    <div class="w3-third w3-right">
      <button class="w3-btn w3-blue w3-large w3-right w3-margin-top" style="margin-bottom: 64px">Guardar rúbrica <i class="far fa-save"></i></button>
    </div>
  </form>
</div>

<!-- modal cambiar nombre -->
<div id="cambiar_nombre" class="w3-modal">
	<div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
    <div class="w3-center"><br>
      <div class="w3-container">
			<span onclick="document.getElementById('cambiar_nombre').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
			<div class="w3-section">
        <label><b>Nombre</b></label>
        <input id="nuevo_nombre" class="w3-input w3-border w3-margin-bottom" type="text" name="nombre" value="{{ rubrica.nombre }}" required>
				<button onclick="cambiar_nombre()" class="w3-button w3-block w3-blue w3-section w3-padding">Cambiar</button>
      </div>
      </div>
		</div>
	</div>
</div>


<script>
  function agregar_criterio() {
    var table = document.getElementById("tabla");
    var cols = table.rows[0].cells.length;
    var rows = table.rows.length;

    // No se crean mas de 8 criterios
    if (rows > 8) return;

    const new_row = table.insertRow(-1);
    for (i = 0; i < cols; i++) {
      const new_cell = document.createElement('td');
      if (i == 0) {
        new_cell.innerHTML = '<span class="w3-button w3-right w3-medium w3-transparent w3-col" style="width:40px"><i class="fas fa-times"></i></span><textarea class="w3-input w3-border" style="resize:none" maxlength="350" rows="2" wrap="soft"></textarea>';
        new_cell.firstChild.setAttribute("onclick", "eliminar_criterio(" + rows.toString() + ")");
        new_cell.lastChild.innerHTML = "Criterio";
      }
      else {
        new_cell.innerHTML = '<textarea class="w3-input w3-border" style="resize:none" maxlength="350" rows="3" wrap="soft"></textarea>';
        new_cell.firstChild.innerHTML = "Descripcion";
      }
      new_cell.lastChild.name = "celda:" + rows.toString() + "," + i.toString();
      new_row.appendChild(new_cell);
    }
  }

  function agregar_nivel() {
    var table = document.getElementById("tabla");
    var cols = table.rows[0].cells.length;
    var rows = table.rows.length;

    // No se crean mas de 6 niveles de cumplimiento
    if (cols > 6) return;
    
    const new_cell = table.rows[0].insertCell(-1);
    new_cell.innerHTML = '<span class="w3-button w3-right w3-medium w3-transparent w3-col" style="width:40px"><i class="fas fa-times"></i></span><input class="w3-input w3-border w3-col" style="width:60px" type="number" min="0" max="6" step="0.1" value="0.0">';
    new_cell.firstChild.setAttribute("onclick", "eliminar_nivel(" + cols.toString() + ")");
    new_cell.lastChild.name = "celda:0," + cols.toString();
    for (i = 1; i < rows; i++) {
      const new_cell = table.rows[i].insertCell(-1);
      new_cell.innerHTML = '<textarea class="w3-input w3-border" style="resize:none" maxlength="350" rows="3" wrap="soft"></textarea>';
      new_cell.firstChild.name = "celda:" + i.toString() + "," + cols.toString();
      new_cell.firstChild.innerHTML = "Descripcion";
    }
  }

  function eliminar_criterio(i) {
    var table = document.getElementById("tabla");
    if (table.rows.length <= 2) return;
    table.rows[i].parentNode.removeChild(table.rows[i]);
    for (j = i; j < table.rows.length; j++) {
      table.rows[j].cells[0].children[0].setAttribute("onclick", "eliminar_criterio(" + j.toString() + ")");
      table.rows[j].cells[0].children[1].name = "celda:" + j.toString() +",0";
      for (k = 1; k < table.rows[j].cells.length; k++)
        table.rows[j].cells[k].children[0].name = "celda:" + j.toString() +","+k.toString();
    }
  }

  function eliminar_nivel(i) {
    var table = document.getElementById("tabla");
    if (table.rows[0].cells.length <= 2) return;
    for (j = 0; j < table.rows.length; j++) {
      table.rows[j].removeChild(table.rows[j].cells[i]);
    }
    for (j = i; j < table.rows[0].cells.length; j++) {
      table.rows[0].cells[j].children[0].setAttribute("onclick", "eliminar_nivel(" + j.toString() + ")");
      table.rows[0].cells[j].children[1].name = "celda:0," + j.toString();
      for (k = 1; k < table.rows.length; k++)
        table.rows[k].cells[j].children[0].name = "celda:" + k.toString() +","+j.toString();
    }
  }

  function cambiar_nombre() {
    var nombre = document.getElementById("nuevo_nombre").value;
    document.getElementById("nombre").value = nombre;
    document.getElementById("nombreTitulo").innerHTML = (nombre + ' <button onclick="document.getElementById(' + "'cambiar_nombre'" + ').style.display='+"'block'" + '" class="w3-button w3-medium w3-transparent w3-display"><i class="fas fa-edit"></i></button>');
    document.getElementById('cambiar_nombre').style.display='none';
  }
</script>

{% endblock %}