Proyecto/iteracion1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sistema.urls')),
]

Proyecto/sistema/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'sistema'

urlpatterns = [
	# LANDING
	path('landingpage/', views.index_landing_admin, name='index_landing_admin'),

    # LOGIN
    path('login/', views.index_login, name = 'index_login'),
    path('login/val', views.login_validate, name = 'login_val'),
    path('logout/', views.log_out, name = 'logout'),
	
    # INDICES
    path('cursos/', views.index_cursos, name = 'index_cursos'),
    path('evaluaciones/', views.index_evaluaciones, name = 'index_evaluaciones'),
    path('evaluadores/', views.index_evaluadores, name = 'index_evaluadores'),
    path('rubricas/', views.index_rubricas, name = 'index_rubricas'),
	
	# EVALUACION
    path('evaluaciones/<int:eval_id>/', views.evaluacion, name = 'evaluacion'),
    path('evaluaciones/<int:eval_id>/agregar', views.evaluacion_agr_evaluador, name='evaluacion_agr_evaluador'),
    path('evaluaciones/<int:eval_id>/eliminar', views.evaluacion_eliminar_evaluador, name='evaluacion_eliminar_evaluador'),
    path('evaluaciones/<int:eval_id>/grupo/<int:grupo_id>/<int:rubrica_id>', views.evaluacion_grupo, name='evaluacion_grupo'),
    path('evaluaciones/<int:eval_id>/grupo/<int:grupo_id>/post/<int:rubrica_id>', views.postevaluacion , name='postevaluacion'),
	
	# RUBRICA
    path('rubricas/<int:rubrica_id>/', views.rubrica, name = 'rubrica'),
    path('rubricas/<int:rubrica_id>/editar', views.rubrica_editar, name = 'rubrica_editar'),
	
	# GESTIONAR EVALUADORES
    path('evaluadores/agregar/', views.agregar_evaluador, name = 'evaluador_agr'),
    path('evaluadores/modificar/', views.modificar_evaluador, name = 'evaluador_mod'),
    path('evaluadores/eliminar/', views.eliminar_evaluador, name = 'evaluador_eli'),
	
	# GESTIONAR RUBRICAS
    path('rubricas/agregar/', views.agregar_rubrica, name = 'rubrica_agr'),
    path('rubricas/<int:rubrica_id>/guardar', views.modificar_rubrica, name = 'rubrica_mod'),
    path('rubricas/eliminar/', views.eliminar_rubrica, name = 'rubrica_eli'),
	
	# GESTIONAR EVALUACIONES
    path('evaluaciones/agregar/', views.agregar_evaluacion, name = 'evaluacion_agr'),
    path('evaluaciones/modificar/', views.modificar_evaluacion, name = 'evaluacion_mod'),
    path('evaluaciones/eliminar/', views.eliminar_evaluacion, name = 'evaluacion_eli'),

    # REDIRECT
    path('', views.home)
]

Proyecto/sistema/models.py
from django.db import models
from django.db import models
from django.utils import timezone

import os

# Create your models here.
from django.utils.datetime_safe import datetime


class Grupo(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre

class Alumno(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField(max_length=90)
    rut = models.CharField(max_length=10)
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class HistorialGrupos(models.Model):
    alumno= models.ForeignKey(Alumno,on_delete=models.CASCADE)
    grupo = models.ForeignKey(Grupo,on_delete=models.CASCADE)
    fecha = models.DateField()

    def __str__(self):
        return self.grupo + ", " + self.fecha

class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre + " " + self.codigo

class Instancia(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    ano=models.IntegerField()
    semestre= models.CharField(max_length=100)
    seccion=models.IntegerField()

    def __str__(self):
        return " ".join([self.curso.nombre, self.semestre, str(self.ano), "Sección", str(self.seccion)])

class InstanciaGrupo(models.Model):
    instancia = models.ForeignKey(Instancia, on_delete=models.CASCADE)#sin on delete tira error
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)#sin on delete tira error

    def __str__(self):
        return str(self.instancia) +" "+ str(self.grupo)

class Evaluacion(models.Model):
    instancia = models.ForeignKey(Instancia, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, default="Evaluacion")
    fecha_inicio=models.DateField()
    fecha_fin=models.DateField()

    def __str__(self):
        return str(self.fecha_inicio)

    # True si fecha_inicio es posterio a fecha actual (al agregar)
    # y fecha_fin es posterior a fecha_inicio
    def validar_fechas(self, agregar=False):
        if agregar and not (self.fecha_inicio >= timezone.now().date()):
            return False
        return self.fecha_inicio <= self.fecha_fin

    # True si fecha actual esta entre fecha_inicio y fecha_fin
    def abierta(self):
        return self.fecha_inicio <= timezone.now().date() <= self.fecha_fin

    # True si la evaluacion ya se realizo
    def realizada(self):
        return self.fecha_fin < timezone.now().date()

class Evaluador(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField(max_length=90)
    password=models.CharField(max_length=100)
    es_admin=models.BooleanField()

    def __str__(self):
        return self.nombre

class Rubrica(models.Model):
    nombre=models.CharField(max_length=100)
    archivo=models.FileField(upload_to=None, max_length=100)
    tiempo_min=models.TimeField(default='00:00:00')
    tiempo_max=models.TimeField(default='00:00:00')
    t = None # tabla donde se guarda la info de archivo

    def __str__(self):
        return self.nombre

    # Crea el archivo y devuelve su ruta
    def crear(self):
        fn = "rubricas/rubrica_{}.csv".format(self.id)
        f = open(fn, "w")
        f.writelines(["$0.0\n","Aspecto1$Descripcion1\n"])
        f.close()
        return fn

    # Carga y devuelve los datos de la rubrica
    def tabla(self):
        if self.t == None:
            f = open(str(self.archivo), "r")
            self.t = [line.rstrip('\n').split('$') for line in f]
            f.close()
        return self.t

    # Devuelvelos niveles de cumplimiento
    def niveles(self):
        if self.t == None:
            self.tabla()
        return self.t[0][1:]

    # Devuelve los aspectos a evaluar
    def aspectos(self):
        if self.t == None:
            self.tabla()
        return [self.t[i][0] for i in range(1, len(self.t))]

    # Borra el archivo asociado
    def borrar(self):
        os.remove(str(self.archivo))

    # Modifica el archivo de acuerdo a la tabla entregada
    def modificar(self, tabla):
        tabla = self.reordenar(tabla)
        f = open(str(self.archivo), "w")
        for linea in tabla:
            f.write("$".join(linea) + "\n")
        self.t = None

    # Reordena las celdas en puntaje de menor a mayor
    def reordenar(self, tabla):
        nt = [[tabla[i].pop(0)] for i in range(len(tabla))]
        while len(tabla[0]) > 0:
            i = tabla[0].index(min(tabla[0]))
            for j in range(len(tabla)):
                nt[j].append(tabla[j].pop(i))
        return nt

    # True si el puntaje maximo es 6.0
    def validar(self):
        t = self.tabla()
        pmax = float(t[0][-1])
        return int(10 * pmax * (len(t) - 1)) == 60

class EvaluacionRubrica(models.Model):
    evaluacion = models.ForeignKey(Evaluacion,on_delete=models.CASCADE)
    rubrica = models.ForeignKey(Rubrica,on_delete=models.CASCADE)

class Presentacion(models.Model):
    presentador=models.CharField(max_length=100)
    evaluador=models.CharField(max_length=100)
    puntajes=models.CharField(max_length=100)
    evaluacion = models.ForeignKey(Evaluacion,on_delete=models.CASCADE)
    tiempo=models.TimeField(default='00:00:00')
    descuento=models.IntegerField(default=0)
    grupo = models.ForeignKey(Grupo,on_delete=models.CASCADE)

class Evalua(models.Model):
    evaluacion = models.ForeignKey(Evaluacion,on_delete=models.CASCADE)
    evaluador = models.ForeignKey(Evaluador,on_delete=models.SET_DEFAULT, default=1)
    puso_nota=models.BooleanField(default=False)


Proyecto/sistema/forms.py
from django import forms

class EvaluadorForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    correo = forms.EmailField(max_length=90)

class EvaluacionForm(forms.Form):
    inicio = forms.DateField()
    fin = forms.DateField()

Proyecto/sistema/templates/sistema/admin/pag_evaluaciones.html
{% extends "sistema/base.html" %}

{% load i18n %}

{% block subtitle %}Evaluaciones{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}
{% block content %}

  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
    <h1 class="w3-xxxlarge w3-text-black"><b>Evaluaciones</b></h1>
    <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
    {% if mensaje %}
			<p style="color:goldenrod"><b>{{ mensaje }}</b></p>
		{% endif %}
  </div>

<div class="w3-container">
    {% if request.session.es_admin %}<button onclick="document.getElementById('agregar').style.display='block'" class="w3-button w3-large w3-blue w3-right w3-round">Agregar nueva evaluación</button><br>   {% endif%}
</div>
<!--Seccion evaluaciones-->

{% for evaluacion in lista_evaluaciones %}
<button onclick="myFunction('Demo{{ forloop.counter }}')" class="w3-btn w3-dark-grey w3-block w3-margin" style="width: 75%"><h3>
    {{ evaluacion.nombre }}</h3></button>

<div id="Demo{{ forloop.counter }}" class="w3-hide w3-container w3-light-grey  w3-padding-large w3-margin"style="width: 75%">

  <p><li>Curso: {{ evaluacion.instancia }}</li>
    <!-- language hace que aparezca la fecha en español -->
    {% language 'es' %}
    <li>Fecha inicio: {{ evaluacion.fecha_inicio }}</li> 
    <li>Fecha término: {{ evaluacion.fecha_fin }}</li>
    {% endlanguage %}
    <a href="{% url 'sistema:rubrica' rubrica_id=evaluacion.evaluacionrubrica_set.all.0.rubrica.id %}"><button class="w3-button w3-white w3-border w3-border-blue w3-round-large">Rúbrica asociada</button></a>
    {% if request.session.es_admin %}<button class="w3-button w3-white w3-border w3-border-blue w3-round-large">Exportar puntajes</button><br>{%endif%}
</p>

  <button onclick="location.href='{% url 'sistema:evaluacion' eval_id=evaluacion.id %}'" class="w3-button w3-large w3-blue w3-round">Ver</button>
  {% if request.session.es_admin %}
  {% if not evaluacion.realizada %}<button onclick="modificar({{ evaluacion.id }}, '{{ evaluacion.nombre }}', '{{ evaluacion.fecha_inicio|date:'Y-m-d' }}', '{{ evaluacion.fecha_fin|date:'Y-m-d' }}',{{ evaluacion.evaluacionrubrica_set.all.0.rubrica.id }},{{ evaluacion.instancia.id }})" class="w3-button w3-large w3-blue w3-margin-left w3-round">Modificar</button>{% endif %}
  <button onclick="eliminar({{ evaluacion.id }})" class="w3-button w3-large w3-blue w3-right w3-round">Eliminar</button>
  {% endif%}
</div>
{% endfor %}

<div style="margin-bottom: 64px">
</div>

<!-- modal de agregar -->
<div id="agregar" class="w3-modal">
  <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
    <div class="w3-center"><br>
      <span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
      <form class="w3-container" action="{% url 'sistema:evaluacion_agr' %}" method="post">
        {% csrf_token %}
        <div class="w3-section">
		  <label><b>Nombre</b></label>
		  <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Ingrese nombre" name="nombre" required>
          <div class="w3-row">
            <div class="w3-half">
              <label><b>Fecha de inicio</b></label>
              <input class="w3-input w3-border w3-margin-bottom" type="date" required name="inicio">
            </div>
            <div class="w3-half">
              <label><b>Fecha de término</b></label>
              <input class="w3-input w3-border w3-margin-bottom" type="date" required name="fin">
            </div>
          </div>

          <label><b>Rúbrica</b></label>
          <select class="w3-select w3-margin-bottom" name="rubrica">
            {% for rubrica in lista_rubricas %}{% if rubrica.validar %}
            <option value="{{ rubrica.id }}">{{ rubrica.nombre }}</option>
            {% endif %}{% endfor %}
          </select>
          <label><b>Curso</b></label>
          <select class="w3-select" name="curso">
            {% for curso in lista_cursos %}
            <option value="{{ curso.id }}">{{ curso }}</option>
            {% endfor %}
          </select>
          <input class="w3-button w3-block w3-blue w3-section w3-padding" type="submit" value="Agregar">
        </div>
      </form>
    </div>
  </div>
</div>

<!-- modal de eliminar -->
<div id="eliminar" class="w3-modal">
  <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
    <div class="w3-center"><br>
      <span onclick="document.getElementById('eliminar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
      <p>¿Está seguro de querer eliminar esta evaluacion?</p>
      <form action="{% url 'sistema:evaluacion_eli' %}" method="post">
        {% csrf_token %}
        <input id="valor_eliminar" type="hidden" name="id" value="">
        <button class="w3-button w3-blue w3-margin-bottom" type="submit">Eliminar</button>
      </form>
    </div>
  </div>
</div>

<!-- modal de modificar -->
<div id="modificar" class="w3-modal">
  <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
    <div class="w3-center"><br>
      <span onclick="document.getElementById('modificar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
      <form class="w3-container" action="{% url 'sistema:evaluacion_mod' %}" method="post">
        {% csrf_token %}
        <div class="w3-section">
          <input id="mod_id" type="hidden" name="id" value="">
		  <label><b>Nombre</b></label>
		  <input id="mod_nombre" class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Ingrese nombre" name="nombre" required>
          <div class="w3-row">
            <div class="w3-half">
              <label><b>Fecha de inicio</b></label>
              <input id="mod_inicio" class="w3-input w3-border w3-margin-bottom" type="date" required name="inicio">
            </div>
            <div class="w3-half">
              <label><b>Fecha de término</b></label>
              <input id="mod_termino" class="w3-input w3-border w3-margin-bottom" type="date" required name="fin">
            </div>
          </div>
          <label><b>Rúbrica</b></label>
          <select id="mod_rubrica" class="w3-select w3-margin-bottom" name="rubrica">
            {% for rubrica in lista_rubricas %}{% if rubrica.validar %}
            <option value="{{ rubrica.id }}">{{ rubrica.nombre }}</option>
            {% endif %}{% endfor %}
          </select>
          <label><b>Curso</b></label>
          <select id="mod_curso" class="w3-select" name="curso">
            {% for curso in lista_cursos %}
            <option value="{{ curso.id }}">{{ curso }}</option>
            {% endfor %}
          </select>
          <input class="w3-button w3-block w3-blue w3-section w3-padding" type="submit" value="Guardar">
        </div>
      </form>
    </div>
  </div>
</div>


<script>
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

  // Abre el modal de eliminar y ajusta el form con el valor correcto
  function eliminar(id) {
		document.getElementById('valor_eliminar').value = id;
		document.getElementById('eliminar').style.display='block';
	}
  function modificar(id, nombre, fecha_i,fecha_t,rubrica,curso) {
		document.getElementById('mod_nombre').value = nombre;
		document.getElementById('mod_inicio').value = fecha_i;
		document.getElementById('mod_termino').value = fecha_t;
		document.getElementById('mod_rubrica').value = rubrica;
		document.getElementById('mod_curso').value = curso;
		document.getElementById('mod_id').value = id;
		document.getElementById('modificar').style.display='block';
  }
</script>

{% endblock %}

Proyecto/sistema/templates/sistema/admin/pag_evaluadores.html
{% extends "sistema/base.html" %}

{% block subtitle %}Evaluaciones{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}

{% block content %}

  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
    <h1 class="w3-xxxlarge w3-text-black"><b>Evaluadores</b></h1>
		<hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
		<p><h3>Seleccione un evaluador</h3></p>
		{% if mensaje %}
			<p style="color:goldenrod"><b>{{ mensaje }}</b></p>
		{% endif %}
  </div>

<!--Cajas evaluadores-->
<div class="w3-row-padding w3-center w3-margin-top" style="margin-bottom: 64px">
	{% for evaluador in lista_evaluadores %}
	<div class="w3-col m6 l4 w3-margin-top">
		<button onclick="modificar({{ evaluador.id }}, '{{ evaluador.nombre }}', '{{ evaluador.correo }}')" class="w3-card w3-container w3-hover-shadow" style="max-height:380px;min-height: 317px; width: 230px">
		<h3>{{ evaluador.nombre }}</h3><br>
		<i class="fas fa-user-alt" style="font-size:100px"></i>
		<p>{{ evaluador.correo|truncatechars:20 }}</p>
		</button>
		<br>
		<button onclick="modificar({{ evaluador.id }}, '{{ evaluador.nombre }}', '{{ evaluador.correo }}')" class="w3-btn w3-blue">Modificar</button>
		<button onclick="eliminar({{ evaluador.id }})" class="w3-btn w3-blue">Eliminar</button>
	</div>
	{% endfor %}
    <!--Caja de agregar-->
	<div class="w3-col m6 l4 w3-margin-top">
		<button onclick="document.getElementById('agregar').style.display='block'" class="w3-card w3-container w3-light-gray w3-hover-shadow" style="min-height: 317px; width: 230px">
		<h3>Agregar evaluador nuevo</h3><br>
		<i class="fas fa-user-plus" style="font-size:80px;text-align: center; padding: 10px"></i>
		</button>
	</div>
<!--cierre de cajas de cursos-->
</div>

<!-- modal de agregar -->
<div id="agregar" class="w3-modal">
	<div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px{% if mensaje %}; display='block'{% endif %}">
		<div class="w3-center"><br>
			<span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
			<form class="w3-container" action="{% url 'sistema:evaluador_agr' %}" method="post">
					{% csrf_token %}
			<div class="w3-section">
				<label><b>Nombre y apellido</b></label>
				<input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Ingrese nombre" name="nombre" required{% if nombre %} value="{{ nombre }}"{% endif %}>
				<label><b>Correo</b></label>
				<input class="w3-input w3-border" type="email" required placeholder="Ingrese correo" name="correo">
				<input class="w3-button w3-block w3-blue w3-section w3-padding" type="submit" value="Agregar">
			</div>
		</form>
		</div>
	</div>
</div>

<!-- modal de modificar -->
<div id="modificar" class="w3-modal">
	<div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px{% if mensaje %}; display='block'{% endif %}">
		<div class="w3-center"><br>
			<span onclick="document.getElementById('modificar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
			<form class="w3-container" action="{% url 'sistema:evaluador_mod' %}" method="post">
					{% csrf_token %}
			<div class="w3-section">
				<input id="mod_id" type="hidden" name="id" value="">
				<label><b>Nombre y apellido</b></label>
				<input id="mod_nombre" class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Ingrese nombre" name="nombre" required>
				<label><b>Correo</b></label>
				<input id="mod_correo" class="w3-input w3-border" type="email" required placeholder="Ingrese correo" name="correo">
				<input class="w3-button w3-block w3-blue w3-section w3-padding" type="submit" value="Guardar">
			</div>
		</form>
		</div>
	</div>
</div>

<!-- modal de eliminar -->
<div id="eliminar" class="w3-modal">
	<div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
		<div class="w3-center"><br>
			<span onclick="document.getElementById('eliminar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
			<p>¿Está seguro de querer eliminar a este usuario?</p>
			<form action="{% url 'sistema:evaluador_eli' %}" method="post">
				{% csrf_token %}
				<input id="valor_eliminar" type="hidden" name="id" value="">
				<button class="w3-button w3-blue w3-margin-bottom" type="submit">Eliminar</button>
			</form>
		</div>
	</div>
</div>

<script>
	// Abre el modal de eliminar y ajusta el form con el valor correcto
	function eliminar(id) {
		document.getElementById('valor_eliminar').value = id;
		document.getElementById('eliminar').style.display='block';
	}
	// Abre el modal de modificar y ajusta el form con los valores correctos
	function modificar(id, nombre, correo) {
		document.getElementById('mod_nombre').value = nombre;
		document.getElementById('mod_correo').value = correo;
		document.getElementById('mod_id').value = id;
		document.getElementById('modificar').style.display='block';
	}
</script>

{% endblock %}

Proyecto/sistema/templates/sistema/admin/pag_rubricas.html
{% extends "sistema/base.html" %}

{% block subtitle %}Rúbricas{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}
{% block content %}

  <!-- Portada -->
  <div class="w3-container" id="portada" style="margin-top:80px; margin-bottom:10px">
    <h1 class="w3-xxxlarge w3-text-black"><b>Rúbricas</b></h1>
    <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
  </div>

<div class="w3-container">
  <button onclick="document.getElementById('agregar').style.display='block'" class="w3-button w3-large w3-blue w3-right w3-round">Agregar nueva rúbrica</button><br>
</div>
<!--Seccion rubricas-->

{% for rubrica in lista_rubricas %}
<button onclick="myFunction('Demo{{ forloop.counter }}')" class="w3-btn w3-dark-grey w3-block w3-margin" style="width: 75%">
  <h3>{{ rubrica.nombre }}</h3></button>

<div id="Demo{{ forloop.counter }}" class="w3-hide w3-container w3-light-grey w3-center w3-padding-large w3-margin"style="width: 75%">
  <p>
    {% for aspecto in rubrica.aspectos %}
    <li>{{ aspecto }}</li>
    {% endfor %}
  </p>
  <div class="w3-container">
    <a href="{% url 'sistema:rubrica' rubrica_id=rubrica.id %}">
      <button class="w3-button w3-large w3-margin-right w3-blue w3-left w3-round">Ver</button>
    </a>
    <a href="{% url 'sistema:rubrica_editar' rubrica_id=rubrica.id %}">
      <button class="w3-button w3-large w3-blue w3-left w3-round">Modificar</button>
    </a>
    <button onclick="eliminar({{ rubrica.id }})" class="w3-button w3-large w3-blue w3-right w3-round">Eliminar</button>
  </div>
</div>
{% endfor %}

<div style="margin-bottom: 64px">
</div>

<!-- modal de agregar -->
<div id="agregar" class="w3-modal">
	<div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
		<div class="w3-center"><br>
			<span onclick="document.getElementById('agregar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
			<form class="w3-container" action="{% url 'sistema:rubrica_agr' %}" method="post">
					{% csrf_token %}
			<div class="w3-section">
        <label><b>Nombre</b></label>
        <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Ingrese nombre" name="nombre" required>
				<input class="w3-button w3-block w3-blue w3-section w3-padding" type="submit" value="Agregar">
			</div>
		</form>
		</div>
	</div>
</div>

<!-- modal de eliminar -->
<div id="eliminar" class="w3-modal">
    <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
      <div class="w3-center"><br>
        <span onclick="document.getElementById('eliminar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
        <p>¿Está seguro de querer eliminar esta rubrica?</p>
        <form action="{% url 'sistema:rubrica_eli' %}" method="post">
          {% csrf_token %}
          <input id="valor_eliminar" type="hidden" name="id" value="">
          <button class="w3-button w3-blue w3-margin-bottom" type="submit">Eliminar</button>
        </form>
      </div>
    </div>
  </div>

<script>
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
	// Abre el modal de eliminar y ajusta el form con el valor correcto
	function eliminar(id) {
		document.getElementById('valor_eliminar').value = id;
		document.getElementById('eliminar').style.display='block';
	}
</script>

{% endblock %}