Proyecto/iteracion1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sistema.urls')),
]

Proyecto/sistema/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'sistema'

urlpatterns = [
	# LANDING
	path('landingpage/', views.index_landing_admin, name='index_landing_admin'),

    # LOGIN
    path('login/', views.index_login, name = 'index_login'),
    path('login/val', views.login_validate, name = 'login_val'),
    path('logout/', views.log_out, name = 'logout'),
	
    # INDICES
    path('cursos/', views.index_cursos, name = 'index_cursos'),
    path('evaluaciones/', views.index_evaluaciones, name = 'index_evaluaciones'),
    path('evaluadores/', views.index_evaluadores, name = 'index_evaluadores'),
    path('rubricas/', views.index_rubricas, name = 'index_rubricas'),
	
	# EVALUACION
    path('evaluaciones/<int:eval_id>/', views.evaluacion, name = 'evaluacion'),
    path('evaluaciones/<int:eval_id>/agregar', views.evaluacion_agr_evaluador, name='evaluacion_agr_evaluador'),
    path('evaluaciones/<int:eval_id>/eliminar', views.evaluacion_eliminar_evaluador, name='evaluacion_eliminar_evaluador'),
    path('evaluaciones/<int:eval_id>/grupo/<int:grupo_id>/<int:rubrica_id>', views.evaluacion_grupo, name='evaluacion_grupo'),
    path('evaluaciones/<int:eval_id>/grupo/<int:grupo_id>/post/<int:rubrica_id>', views.postevaluacion , name='postevaluacion'),
	
	# RUBRICA
    path('rubricas/<int:rubrica_id>/', views.rubrica, name = 'rubrica'),
    path('rubricas/<int:rubrica_id>/editar', views.rubrica_editar, name = 'rubrica_editar'),
	
	# GESTIONAR EVALUADORES
    path('evaluadores/agregar/', views.agregar_evaluador, name = 'evaluador_agr'),
    path('evaluadores/modificar/', views.modificar_evaluador, name = 'evaluador_mod'),
    path('evaluadores/eliminar/', views.eliminar_evaluador, name = 'evaluador_eli'),
	
	# GESTIONAR RUBRICAS
    path('rubricas/agregar/', views.agregar_rubrica, name = 'rubrica_agr'),
    path('rubricas/<int:rubrica_id>/guardar', views.modificar_rubrica, name = 'rubrica_mod'),
    path('rubricas/eliminar/', views.eliminar_rubrica, name = 'rubrica_eli'),
	
	# GESTIONAR EVALUACIONES
    path('evaluaciones/agregar/', views.agregar_evaluacion, name = 'evaluacion_agr'),
    path('evaluaciones/modificar/', views.modificar_evaluacion, name = 'evaluacion_mod'),
    path('evaluaciones/eliminar/', views.eliminar_evaluacion, name = 'evaluacion_eli'),

    # REDIRECT
    path('', views.home)
]

Proyecto/sistema/models.py
from django.db import models
from django.db import models
from django.utils import timezone

import os

# Create your models here.
from django.utils.datetime_safe import datetime


class Grupo(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre

class Alumno(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField(max_length=90)
    rut = models.CharField(max_length=10)
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class HistorialGrupos(models.Model):
    alumno= models.ForeignKey(Alumno,on_delete=models.CASCADE)
    grupo = models.ForeignKey(Grupo,on_delete=models.CASCADE)
    fecha = models.DateField()

    def __str__(self):
        return self.grupo + ", " + self.fecha

class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre + " " + self.codigo

class Instancia(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    ano=models.IntegerField()
    semestre= models.CharField(max_length=100)
    seccion=models.IntegerField()

    def __str__(self):
        return " ".join([self.curso.nombre, self.semestre, str(self.ano), "Sección", str(self.seccion)])

class InstanciaGrupo(models.Model):
    instancia = models.ForeignKey(Instancia, on_delete=models.CASCADE)#sin on delete tira error
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)#sin on delete tira error

    def __str__(self):
        return str(self.instancia) +" "+ str(self.grupo)

class Evaluacion(models.Model):
    instancia = models.ForeignKey(Instancia, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, default="Evaluacion")
    fecha_inicio=models.DateField()
    fecha_fin=models.DateField()

    def __str__(self):
        return str(self.fecha_inicio)

    # True si fecha_inicio es posterio a fecha actual (al agregar)
    # y fecha_fin es posterior a fecha_inicio
    def validar_fechas(self, agregar=False):
        if agregar and not (self.fecha_inicio >= timezone.now().date()):
            return False
        return self.fecha_inicio <= self.fecha_fin

    # True si fecha actual esta entre fecha_inicio y fecha_fin
    def abierta(self):
        return self.fecha_inicio <= timezone.now().date() <= self.fecha_fin

    # True si la evaluacion ya se realizo
    def realizada(self):
        return self.fecha_fin < timezone.now().date()

class Evaluador(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField(max_length=90)
    password=models.CharField(max_length=100)
    es_admin=models.BooleanField()

    def __str__(self):
        return self.nombre

class Rubrica(models.Model):
    nombre=models.CharField(max_length=100)
    archivo=models.FileField(upload_to=None, max_length=100)
    tiempo_min=models.TimeField(default='00:00:00')
    tiempo_max=models.TimeField(default='00:00:00')
    t = None # tabla donde se guarda la info de archivo

    def __str__(self):
        return self.nombre

    # Crea el archivo y devuelve su ruta
    def crear(self):
        fn = "rubricas/rubrica_{}.csv".format(self.id)
        f = open(fn, "w")
        f.writelines(["$0.0\n","Aspecto1$Descripcion1\n"])
        f.close()
        return fn

    # Carga y devuelve los datos de la rubrica
    def tabla(self):
        if self.t == None:
            f = open(str(self.archivo), "r")
            self.t = [line.rstrip('\n').split('$') for line in f]
            f.close()
        return self.t

    # Devuelvelos niveles de cumplimiento
    def niveles(self):
        if self.t == None:
            self.tabla()
        return self.t[0][1:]

    # Devuelve los aspectos a evaluar
    def aspectos(self):
        if self.t == None:
            self.tabla()
        return [self.t[i][0] for i in range(1, len(self.t))]

    # Borra el archivo asociado
    def borrar(self):
        os.remove(str(self.archivo))

    # Modifica el archivo de acuerdo a la tabla entregada
    def modificar(self, tabla):
        tabla = self.reordenar(tabla)
        f = open(str(self.archivo), "w")
        for linea in tabla:
            f.write("$".join(linea) + "\n")
        self.t = None

    # Reordena las celdas en puntaje de menor a mayor
    def reordenar(self, tabla):
        nt = [[tabla[i].pop(0)] for i in range(len(tabla))]
        while len(tabla[0]) > 0:
            i = tabla[0].index(min(tabla[0]))
            for j in range(len(tabla)):
                nt[j].append(tabla[j].pop(i))
        return nt

    # True si el puntaje maximo es 6.0
    def validar(self):
        t = self.tabla()
        pmax = float(t[0][-1])
        return int(10 * pmax * (len(t) - 1)) == 60

class EvaluacionRubrica(models.Model):
    evaluacion = models.ForeignKey(Evaluacion,on_delete=models.CASCADE)
    rubrica = models.ForeignKey(Rubrica,on_delete=models.CASCADE)

class Presentacion(models.Model):
    presentador=models.CharField(max_length=100)
    evaluador=models.CharField(max_length=100)
    puntajes=models.CharField(max_length=100)
    evaluacion = models.ForeignKey(Evaluacion,on_delete=models.CASCADE)
    tiempo=models.TimeField(default='00:00:00')
    descuento=models.IntegerField(default=0)
    grupo = models.ForeignKey(Grupo,on_delete=models.CASCADE)

class Evalua(models.Model):
    evaluacion = models.ForeignKey(Evaluacion,on_delete=models.CASCADE)
    evaluador = models.ForeignKey(Evaluador,on_delete=models.SET_DEFAULT, default=1)
    puso_nota=models.BooleanField(default=False)


Proyecto/sistema/forms.py
from django import forms

class EvaluadorForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    correo = forms.EmailField(max_length=90)

class EvaluacionForm(forms.Form):
    inicio = forms.DateField()
    fin = forms.DateField()

Proyecto/sistema/templates/sistema/evaluacion/evaluacion.html
{% extends "sistema/base.html" %}

{% block subtitle %}Evaluación{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}

{% block content %}

{% load staticfiles %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <!-- Evaluacion -->
  <div class="w3-container" id="designers">
    <h1 class="w3-xxxlarge w3-text-black"><b>Evaluación <i class="w3-text-green">en curso</i> </b></h1>
    <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
    <div class="w3-container w3-center">
        <p><b>{{grupo.nombre}} </b> {{ evaluacion.nombre }} <i>{{ evaluacion.instancia }}</i></p>

	{% block eval_admin %}{% endblock %}
	
    <p>Seleccione el nivel de logro alcanzado por el grupo en cada ámbito</p>
    </div>
{% for fila in rubrica.tabla %}
    {% if not forloop.first %}
    <div class="w3-panel  w3-margin-bottom">
      <ul class="w3-ul w3-light-grey w3-center w3-card-4" name="aspectos">
           {% for celda in fila %}
          {% if forloop.first %}
        <li class="w3-dark-grey w3-xlarge w3-padding-32">{{ celda }}
            <!--<i class="far fa-check-circle"></i>--></li>
         {% else %}
          <li class="opcion w3-padding-16" onclick="selector(this);" name="cumplimientos-{{forloop.counter}}"> {{ celda }}

          </li>

          {% endif %}


              {% endfor %}

        </ul>
    </div>

  {% endif %}
      {% endfor %}

            <div class="w3-panel" style="width: 50%; margin:auto;">
                <form class="w3-center"  id="form_puntajes" method="post" action="{% url 'sistema:postevaluacion' eval_id=evaluacion.id grupo_id=grupo.id rubrica_id=evaluacion.evaluacionrubrica_set.all.0.rubrica.id %}" >
                        {% csrf_token %}
                <input id="puntaje" type="text" name="lista-puntajes" style="display:none"  value="1">
                <input id="puntajes-base" type="text" name="lista-pj-base" style="display:none" value="{{rubrica.tabla.0}}" >
                {% block eval_admin_tiempo %}{% endblock %}
                <br>

                <button class="w3-button w3-xlarge w3-blue w3-center" onclick="return obtener()"><i class="fas fa-envelope-open-text"> </i> Enviar</button>
                </form>
            </div>



  </div>

     <!--Modalidad confirmacion -->
	 <div id="confirmacion" class="w3-modal">
	    <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
		    <div class="w3-center"><br>
			    <span onclick="document.getElementById('confirmacion').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
			    <p>¿Está seguro de enviar la evaluación?</p>
				    {% csrf_token %}
				    <input id="valor_eliminar" type="hidden" name="id" value="">
				    <button class="w3-button w3-blue w3-margin-bottom"  id="SI" value="-">Si</button>
                    <button class="w3-button w3-blue w3-margin-bottom" id="NO" value="-">No</button>
		    </div>
	    </div>
     </div>


<script>
  function selector(element) {
        var row = element.parentNode;
        for (var i = 0; i < row.children.length; i++) {
            if (!row.children.item(i).classList.contains("row-name")) {
                row.children.item(i).classList.remove("selected");
            }
        }
        element.classList.add("selected");
  }

  function obtener(){
            var largoaspectos=document.getElementsByName("aspectos").length;
            var puntajes=document.getElementsByClassName("selected");
            //Confirmacion de puntajes
            if(puntajes.length!= largoaspectos ){
                    alert("Se debe seleccionar puntaje para cada aspecto");
                    document.getElementById("form_puntajes").addEventListener("submit", function(event){
                         event.preventDefault()
                    });
            }
            else{
                document.getElementById("form_puntajes").addEventListener("submit", function(event)
                {
                event.preventDefault()
                });
                document.getElementById("confirmacion").style.display='block';
            }
  }
  document.getElementById("SI").addEventListener("click", function () {
           document.getElementById("confirmacion").style.display='none';
           //Lista con los puntajes seleccionados
           var list=[];
           var largoaspectos=document.getElementsByName("aspectos").length;
           var puntajes=document.getElementsByClassName("selected");
           for(var i=0; i<largoaspectos;i++){
               var listado=puntajes[i].innerText.split(" ");
               list.push(listado[listado.length-1]);
           }
           var punt=document.getElementById("puntaje");
           punt.value=list;
           document.getElementById("form_puntajes").submit();
  })
  document.getElementById("NO").addEventListener("click", function () {
          document.getElementById("confirmacion").style.display='none';
  })



  var i=0;
  listado_puntajes='{{puntajes}}';
  var patron= /&#39;/g;
  listado_puntajes=listado_puntajes.replace(patron,'').replace('[','').replace(']','').split(',');
  for(var i = 0; i < listado_puntajes.length; i++){
        //Saco los cumplimientos para el puntaje que le asignare
        var name='cumplimientos-'+((i+2));
        var aspec=document.getElementsByName(name);
        for(var j=0;j<aspec.length;j++){
        //Coloco los puntajes
            aspec[j].innerHTML=aspec[j].innerHTML+ '<p  style="font-weight:bold"> Puntaje: '+listado_puntajes[i]+'</p>';
        }
  }
</script>

{% endblock %}

Proyecto/sistema/templates/sistema/evaluacion/gruposevaluacion.html
{% extends "sistema/base.html" %}

{% load i18n %}

{% block subtitle %}Evaluación{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}
{% block content %}

 <div class="w3-container" id="designers" style="margin-top:50px">
    <h1 class="w3-xxxlarge w3-text-black"><b>Evaluación
	{% if evaluacion.abierta %}<i class="w3-text-green">en curso</i>{% else %}cerrada{% endif %}</b></h1>
    <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
    <div class="w3-container w3-center">
    <h3>{{ evaluacion.nombre }} <i>{{ evaluacion.instancia }}</i></h3>
	    {% language 'es' %}
		 <h3>Fecha inicio: {{ evaluacion.fecha_inicio }}</h3>
		 <h3>Fecha termino: {{ evaluacion.fecha_fin }}</h3>
		 <h3>Tiempo minimo: {{ evaluacion.evaluacionrubrica_set.all.0.rubrica.tiempo_min }} minutos</h3>
		 <h3>Tiempo máximo: {{ evaluacion.evaluacionrubrica_set.all.0.rubrica.tiempo_max }}  minutos</h3>
		{% endlanguage %}
    </div>
     <!--Cajas evaluadores-->
	 {%if request.session.es_admin %}
	 	 <div class="w3-container" style="margin-top:50px">
    <h1 class="w3-xxxlarge w3-text-black"><b>Evaluadores</b></h1>
    <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
    <div class="w3-container w3-center">
	</div>

	     <div class="w3-panel  w3-margin-bottom">
      <ul class="w3-ul w3-light-grey w3-center w3-card-4">
        <li class="w3-dark-grey w3-xlarge w3-padding-32">Evaluadores <i class="fas fa-user-tie"></i> </li>
		  {%for evalua in lista_evalua%}
        <li class="w3-padding-16"> {{evalua.evaluador.nombre}} <i style="margin-left: 10px" class="w3-large fas fa-times" onclick="eliminar({{evalua.evaluador.id}})"></i>
          </li>
		  {%endfor%}
       <!--<i class="w3-small"> ya evaluó</i></i>-->
           </li>
          <li class="opcion w3-padding-16" onclick="agregar('agregar_evaluador')"> Agregar <i style="margin-left: 10px" class="fas fa-user-plus"></i>
           </li>
      </ul>
    </div>
			 	 {%endif%}
		 </div>
     <!--Modalidad agregar evaluador de evaluacion-->
	<div id="agregar_evaluador" class="w3-modal">
  <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
    <div class="w3-center"><br>
      <span onclick="document.getElementById('agregar_evaluador').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
      <form class="w3-container" action="{% url 'sistema:evaluacion_agr_evaluador' eval_id=evaluacion.id %}" method="post">
        {% csrf_token %}
        <div class="w3-section">
          <label><b>Evaluador</b></label>
          <select class="w3-select" name="evalu">
			{%for evaluador in lista_evaluadores%}
            <option value="{{ evaluador.id }}">{{evaluador.nombre}}</option>
			{%endfor%}
          </select>
          <button class="w3-button w3-blue w3-margin-bottom" type="submit">Agregar</button>
        </div>
      </form>
    </div>
  </div>
</div>
     <!--Modalidad eliminar evaluador de evaluacion-->
	 <div id="eliminar" class="w3-modal">
	<div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">
		<div class="w3-center"><br>
			<span onclick="document.getElementById('eliminar').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
			<p>¿Está seguro de querer eliminar a este evaluador de la evaluación?</p>
			<form action="{% url 'sistema:evaluacion_eliminar_evaluador' eval_id=evaluacion.id %}" method="post">
				{% csrf_token %}
				<input id="valor_eliminar" type="hidden" name="id" value="">
				<button class="w3-button w3-blue w3-margin-bottom" type="submit">Eliminar</button>
			</form>
		</div>
	</div>
</div>

	 <div class="w3-container" style="margin-top:50px">
    <h1 class="w3-xxxlarge w3-text-black"><b>Grupos</b></h1>
    <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
    <div class="w3-container w3-center">
	</div>
     <!--Cajas grupos-->
<div class="w3-row-padding w3-center w3-margin-top">
	{% for grupo in lista_grupos %}
	<div class="w3-col m6 l4 w3-margin-top">
		<button class="w3-card w3-container w3-hover-shadow w3-light-gray" style="max-height:380px;min-height: 317px; width:220px">
		<h3>{{ grupo.grupo.nombre }}</h3>
		<br>
		<ul>
			{% for alumno in grupo.grupo.alumno_set.all %}
			<li>{{ alumno.nombre }}</li>
			{% endfor %}
		</ul>
		</button>
		<br>
		{% if evaluacion.abierta %}<button onclick="location.href='{% url 'sistema:evaluacion_grupo' eval_id=evaluacion.id grupo_id=grupo.id rubrica_id=evaluacion.evaluacionrubrica_set.all.0.rubrica.id %}'" class="w3-btn w3-blue">Evaluar</button>{% endif %}
	</div>
	{% endfor %}
</div>
	 </div>
	 	 </div>
<br>

	 <script>
		  function agregar(id) {
		document.getElementById('agregar_evaluador').style.display='block';
	}
		function eliminar(id) {
		document.getElementById('valor_eliminar').value = id;
		document.getElementById('eliminar').style.display='block';
	}
	 </script>
{% endblock %}

Proyecto/sistema/templates/sistema/evaluacion/posteval.html
{% extends "sistema/base.html" %}

{% block subtitle %}Evaluación{% endblock %}
{% block user %} {{request.session.nombre}}{% endblock %}
{% block content %}

  <!-- Evaluacion -->
  <div class="w3-container" id="designers" style="margin-top:50px">
    <h1 class="w3-xxxlarge w3-text-black"><b>Evaluación <i class="w3-text-blue">entregada</i> </b></h1>
    <i class="w3-large w3-text-green"><i class="far fa-clock">

        {% if evaluacion.abierta %}</i> Aún activa </i>{% else %}</i> Cerrada </i>{% endif %}</b></h1>
    <hr style="width:50px;border:5px solid #2FA0FB" class="w3-round">
    <div class="w3-container w3-center">
  <p><b>{{grupo.nombre}} </b> {{ evaluacion.nombre }} <i>{{ evaluacion.instancia }}</i></p>
    <p><i class="w3-text-blue">Su operación se ha procesado exitosamente!</i></p> </div>
    
    <div class="w3-container">
            <h4><b>Resumen de evaluación</b></h4>
        {% for fila in rubrica.tabla %}
        {% if not forloop.first %}
        {% for celda in fila %}
        {% if forloop.first %}
            <p>{{celda}} </p>


            <div class="w3-grey">
                <div class="w3-container w3-center w3-padding w3-white" name="aspecto" ></div>
            </div>
         {% endif %}
         {% endfor %}
           {% endif %}
        {% endfor %}

{% block post_admin %}

            <div class="w3-panel w3-right w3-half" style="margin-top: 50px">
                   <button onclick="location.href='{% url 'sistema:evaluacion_grupo' eval_id=evaluacion.id grupo_id=grupo.id rubrica_id=evaluacion.evaluacionrubrica_set.all.0.rubrica.id %}'"class="w3-button w3-xlarge w3-blue w3-margin-bottom" style="margin-left: 15%"> <i class="fas fa-pen"></i>  Editar evaluación</button>
                    <a href="{% url 'sistema:evaluacion' eval_id=evaluacion.id %}"><button class="w3-button w3-xlarge w3-blue" style="margin-left: 15%"> <i class="fas fa-door-open"></i> Volver a grupos</button></a>

                </div>
{% endblock %}
   
  </div>
 
</div>

<script>

 puntaje_base='{{puntaje_base}}';
 var patron= /&#39;/g;
 puntaje_base=puntaje_base.replace(patron,'').replace('[','').replace(']','').split(',');
 listado_puntajes='{{puntajes}}';
 listado_puntajes=listado_puntajes.replace(patron,'').replace('[','').replace(']','').split(',');
 for(var i = 0; i < listado_puntajes.length; i++){
   var aspec=document.getElementsByName('aspecto')[i];
   var porcentaje=100/(puntaje_base.length-2);
   var porcentaje_final=0;
   //Saca porcentaje
   for (var j=1;j<puntaje_base.length;j++){
        if (parseFloat(listado_puntajes[i])==0){
            break;
        }
        if (parseFloat(listado_puntajes[i])==parseFloat(puntaje_base[j])){
            break;
        }

       porcentaje_final+=porcentaje;
   }
   if(porcentaje_final==0){
      porcentaje_final_barra=5;
   }
   else{
      porcentaje_final_barra=porcentaje_final;
    }
   aspec.innerHTML='<div class="w3-container w3-center w3-padding w3-gray" name="aspecto-i" style="width:'+Math.round(porcentaje_final_barra)+'% "'+'>'+Math.round(porcentaje_final)+'% '+'</div>';
 }

</script>

{% endblock %}
#TODO: FALTA GUARDAR EN BASE DE DATOS

Proyecto/sistema/templates/sistema/evaluacion/postevaladmin.html
{% extends "sistema/evaluacion/posteval.html" %}

{% block post_admin %}
<br>
            {% if descuento != 0 %}<p class="w3-text-black w3-center"> Se aplico un descuento de {{descuento}}</p>{%endif%}

            <div class="w3-row-padding" style="margin-top:100px">
                <div class="w3-half w3-margin-bottom ">
                    <ul class="w3-ul w3-light-grey w3-center w3-card-4">
                      <li class="w3-blue w3-xlarge w3-padding-32">Equipos pendientes<i style="margin-left: 10px" class="fas fa-user-friends"></i><br> <i class="w3-small">Comience una nueva evaluación ...</i></li>
                      <li class="opcion w3-padding-16">Equipo Rocket <i style="margin-left: 10px" class="w3-xlarge fas fa-play-circle"></i></li>
                      <li class="opcion w3-padding-16">Equipo Ejemplo <i style="margin-left: 10px" class="w3-xlarge fas fa-play-circle"></i></li>
                      <li class="opcion presentado w3-padding-16">Equipo 7 <i style="margin-left: 10px" class="w3-xlarge fas fa-play-circle"></i></li>
                      <li class="opcion w3-padding-16">Equipo Example <i style="margin-left: 10px" class="w3-xlarge fas fa-play-circle"></i></li>
                    </ul>
                </div>
                <div class="w3-half" >
                   <button onclick="location.href='{% url 'sistema:evaluacion_grupo' eval_id=evaluacion.id grupo_id=grupo.id rubrica_id=evaluacion.evaluacionrubrica_set.all.0.rubrica.id %}'"class="w3-button w3-xlarge w3-blue w3-margin-bottom" style="margin-left: 15%"> <i class="fas fa-pen"></i>  Editar evaluación</button>
                    <button disabled class="w3-btn w3-xlarge w3-dark-grey" style="margin-left: 15%" > <i class="fas fa-door-open"></i> Exportar resultados</button>

                </div>
            </div>

<script>

</script>
{% endblock %}